In [1]:
# import required libraries
import numpy as np

In [5]:
# create a random matrix

# declare rows and columns
rows = 4
columns = 4

# declare high and low value
low = 0
high = 10

rand_matrix1 = np.random.randint(low, high, size = (rows, columns))

rand_matrix1

array([[8, 3, 3, 2],
       [7, 6, 3, 5],
       [6, 1, 6, 1],
       [4, 8, 5, 6]])

In [6]:
# add another matrix
rand_matrix2 = np.random.randint(low, high, size = (rows, columns))

rand_matrix2

array([[5, 9, 5, 8],
       [0, 8, 8, 6],
       [0, 4, 1, 6],
       [9, 6, 5, 5]])

In [7]:
# addition of two matrices
add_matrix = rand_matrix1 + rand_matrix2
add_matrix

array([[13, 12,  8, 10],
       [ 7, 14, 11, 11],
       [ 6,  5,  7,  7],
       [13, 14, 10, 11]])

In [8]:
# loop in resultant matrix
for i in add_matrix:
    print(i)

[13 12  8 10]
[ 7 14 11 11]
[6 5 7 7]
[13 14 10 11]


In [12]:
# loop through every element and add into list
list = []

for i in add_matrix:
    for j in i:
        list.append(j)
list

[13, 12, 8, 10, 7, 14, 11, 11, 6, 5, 7, 7, 13, 14, 10, 11]

In [14]:
# matrix multiplication
multi_matrix = rand_matrix1 * rand_matrix2
multi_matrix

array([[40, 27, 15, 16],
       [ 0, 48, 24, 30],
       [ 0,  4,  6,  6],
       [36, 48, 25, 30]])

In [16]:
div_matrix = multi_matrix/2
div_matrix

array([[20. , 13.5,  7.5,  8. ],
       [ 0. , 24. , 12. , 15. ],
       [ 0. ,  2. ,  3. ,  3. ],
       [18. , 24. , 12.5, 15. ]])

In [10]:
len(list)

4

In [7]:
# access random value
rand_matrix[0][0], rand_matrix[0][1], rand_matrix[0][2], rand_matrix[0][3]

(5, 37, 96, 63)

In [8]:
rand_matrix[1][0], rand_matrix[1][1], rand_matrix[1][2], rand_matrix[1][3]

(37, 61, 31, 31)

In [9]:
rand_matrix[3][3]

83